index:
   path: /profil/{subpage}/{page}
   defaults: {_controller: AppBundle:Main_Page:index,page:1}
galery:
   path: /profil/galeria/album/{album_id}/page/{page}
   defaults: {_controller: AppBundle:Main_Page:galery,page:1}  
image_upload:
   path: /profil/galeria/album/{album_id}/page/{page}/upload
   defaults: {_controller: AppBundle:Main_Page:upload,page:1}
album_access:
   path: /profil/galeria/album/{album_id}/page/{page}/dostep
   defaults: {_controller: AppBundle:Main_Page:album_access,page:1}  
change_album_name:
   path: /profil/galeria/album/{album_id}/zmien-nazwe-albumu
   defaults: {_controller: AppBundle:Main_Page:change_album_name}  
delete_album:
   path: /profil/galeria/album/{album_id}/page/{page}/usun-album
   defaults: {_controller: AppBundle:Main_Page:delete_album,page:1}   
add_album:
   path: /profil/galeria/{page}/dodaj-album
   defaults: {_controller: AppBundle:Main_Page:add_album,page:1}      
   
image:
   path: /profil/galeria/album/{album_id}/zdjecie/{image_id}
   defaults: {_controller: AppBundle:Main_Page:images}     
edit_img_description:   
   path: /profil/galeria/album/{album_id}/zdjecie/{image_id}/edytuj_opis
   defaults: {_controller: AppBundle:Main_Page:edit_img_description}
delete_image:
   path: /profil/galeria/album/{album_id}/zdjecie/{image_id}/usun-zdjecie
   defaults: {_controller: AppBundle:Main_Page:delete_img}
set_as_profile_img:
   path: /profil/galeria/album/{album_id}/zdjecie/{image_id}/profilowe
   defaults: {_controller: AppBundle:Main_Page:set_as_profile_img}
login:
   path: /login
   defaults: {_controller: AppBundle:Login:index}
register:
   path: /login/rejestracja
   defaults: {_controller: AppBundle:Login:register}
signin:
   path: /login/logowanie
   defaults: {_controller: AppBundle:Login:login}
signout:
   path: /wyloguj
   defaults: {_controller: AppBundle:Login:signout}

search:
   path: /wyszukiwarka/{page}
   defaults: {_controller: AppBundle:Search:index,page:1}
add_to_friends:
   path: /wyszukiwarka/{page}/add-to-friends
   defaults: {_controller: AppBundle:Friends:add_to_friends,page:1}

add_to_friends2:
   path: /user/{user_id}/{subpage}/{page}/add-to-friends
   defaults: {_controller: AppBundle:Friends:add_to_friends,page:1}
delete_friend:
   path: /profil/znajomi/{page}/delete-friend
   defaults: {_controller: AppBundle:Friends:delete_friend,page:1}
user_profile:
   path: /user/{user_id}/{subpage}/{page}
   defaults: {_controller: AppBundle:User_profile:show_profile,page:1}
other_user_galery:
   path: /user/{user_id}/galeria/album/{album_id}/page/{page}
   defaults: {_controller: AppBundle:User_profile:other_user_galery,page:1}
   
other_user_image:
   path: /user/{user_id}/galeria/album/{album_id}/zdjecie/{image_id}
   defaults: {_controller: AppBundle:User_profile:other_user_images} 